name: Windows Builds
on: [push, pull_request]

env:
  GODOT_BASE_BRANCH: master

jobs:
  build-windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Editor build
            target: release_debug
            tools: true
          - name: Template build
            target: release
            tools: false
            sconsflags: debug_symbols=no
    steps:
      # Setup python
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
          architecture: "x64"
      # Install scons
      - name: Setup scons
        shell: bash
        run:  |
          python -c "import sys; print(sys.version)"
          python -m pip install scons
          scons --version
    
      - name: Clone godot
        uses: actions/checkout@v2
        with:
          name: Godot
          ref: refs/heads/master
          repository: godotengine/godot
        
